#SERVER
server.port=8080

#DATASOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/finance
spring.datasource.username=postgres
spring.datasource.password=xxxxxxxxx

#JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#JWT CONFIG
app.jwt.issuer=finance-aggregator
app.jwt.secret=xxxxxxxxxxx
app.jwt.expirationMinutes=120

#CRYPTO CONFIG
app.crypto.key=xxxxxxxxxxxxxx

#PLAID CONFIG
plaid.baseUrl=https://sandbox.plaid.com
plaid.clientId=xxxxxxxxxxxx
plaid.secret=xxxxxxxxxxx